# (PART) Mathematische Grundlagen {-}

# Mengen {#mengen}


```{definition, name =  "Mengen und Mengendefinition"}

Nach @cantor_beitrage_1895 ist eine *Menge* definiert als 
"eine Zusammenfassung $M$ von bestimmten wohlunterschiedenen Objekten $m$ unsere
Anschauung oder unseres Denken (welche die Elemente der Menge genannt werden) 
zu einem Ganzen". Wir schreiben
\begin{equation}
m \in M \mbox{ bzw. } m \notin M
\end{equation}
um auszudrücken, dass $m$ ein Element bzw. kein Element von $M$ ist. Zur 
Definition von Mengen gibt es mindestens folgende Möglichkeiten:

* Auflisten der Elemente in geschweiften Klammern, z.B. $M := \{1,2,3\}$.
* Angabe der Eigenschaften der Elemente, z.B. $M := \{x \in \mathbb{N}|x < 4\}$.
* Gleichsetzen mit einer anderen eindeutig definieren Menge, z.B.
$M := \mathbb{N}_3$.

```

Bemerkungen

* (2) wird als ``$x \in \mathbb{N}$, für die gilt, dass $x < 4$ ist'' gelesen.
* Die Bedeutung von $\mathbb{N}$ und $\mathbb{N}_3$ wird im Folgenden erläutert.
* Mengen sind *ungeordnet*, d.h. $\{1,2,3\} = \{1,3,2\} = \{2,3,1\}$ etc.


```{definition, name = "Teilmengen und Mengengleichheit"}

* Eine Menge $A$ heißt *Teilmenge* einer Menge $B$, wenn für jedes Element 
$a \in A$ gilt, dass auch $a\in B$. Ist $A$ eine Teilmenge von $B$, so schreibt 
man
\begin{equation}
A \subseteq B 
\end{equation}
und nennt $A$ *Untermenge* von $B$ und $B$ *Obermenge* von $A$.

* Eine Menge $A$ heißt *echte Teilmenge* einer Menge $B$, wenn für jedes Element
$a \in A$ gilt, dass auch $a\in B$, es aber zumindest ein Element $b \in B$ gibt, 
für das gilt $b \notin A$. Ist $A$ eine echte Teilmenge von $B$, so schreibt man
\begin{equation}
A \subset B.
\end{equation}

* Zwei Mengen $A$ und $B$ heißen *gleich*, wenn für jedes Element $a \in A$ gilt,
dass auch $a \in B$, und wenn für jedes Element $b \in B$ gilt, dass auch $b 
\in A$. Sind die Mengen $A$ und $B$ gleich, so schreibt man
\begin{equation}
A = B.
\end{equation}

```

Betrachten wir zum Beispiel die Mengen $A := \{1\}$, $B := \{1,2\}$, und
$C := \{1,2\}$. Dann gilt mit obigen Definitionen, dass $A \subset B$, 
$B \subseteq C$, $C \subseteq B$ und $B = C$.


```{definition, name = "Kardinalität, leere Menge"}
Die Anzahl der Elemente einer Menge $M$ heißt *Kardinalität* und wird mit
$|M|$ bezeichnet. Eine Menge mit Kardinalität Null heißt *leere Menge* und wird 
mit $\emptyset$ bezeichnet.
```


Betrachten wir zum Beispiel die Menge $M := \{1,2,3\}$. Dann gilt $|M| = 3$.

```{definition, name = "Potenzmenge"}

Die Menge aller Teilmengen einer Menge $M$ heißt *Potenzmenge von $M$* und 
wird mit $\mathcal{P}(M)$ bezeichnet. Die leere Untermenge von $M$ und $M$ 
selbst sind immer Elemente von $\mathcal{P}(M)$.

```

Die Potenzmenge der Menge $M := \{1,2,3\}$ ist also die Menge aller Teilmengen
von $M$. Es gilt also 
$\mathcal{P}(M) = \{\emptyset, \{1\},\{2\},\{3\},\{1,2\},\{1,3\},\{2,3\},\{1,2,3\}\}$.
Man kann zeigen, dass aus $|M| = n$ folgt, dass $|\mathcal{P}(M)| = 2^n$.


```{definition, name = "Mengenoperationen"}
$M$ und $N$ seien zwei Mengen.

* Die *Vereinigung von $M$ und $N$* ist definiert als die Menge
\begin{equation}
M \cup N := \{x | x \in M \mbox{ oder } x \in N\},
\end{equation}
wobei *oder* im inklusiven Sinne als *und/oder* zu verstehen ist.

* Der *Durchschnitt von $M$ und $N$* ist definiert als die Menge
\begin{equation}
M \cap N := \{x | x \in M \mbox{ und } x \in N\}.
\end{equation}

* Die *Differenz von $M$ und $N$* ist definiert als die Menge
\begin{equation}
M\setminus N := \{x | x \in M \mbox{ und } x \notin N\}.
\end{equation}

* Die *symmetrische Differenz von $M$ und $N$* ist definiert als die Menge
\begin{equation}
M \Delta N := \{x|x \in M \mbox{ oder } x \in N, 
\mbox{ aber } x \notin M \cap N\},
\end{equation}
wobei *oder* hier also im exklusiven Sinne zu verstehen ist.

```


Bemerkung

- Für $M := \{1,2,3\}$ und $N := \{2,3,4,5\}$ gilt
\begin{equation*}
M \cup N = \{1,2,3,4,5\}, M \cap N = \{2,3\}, M \setminus N = \{1\}, N \setminus M = \{4,5\}, M \Delta N = \{1,4,5\}.
\end{equation*}




```{definition, name = "Zahlenmengen"}

Es bezeichnen

* $\mathbb{N}\,\,\, := \{1,2,3,...\}$ die *natürlichen Zahlen*
* $\mathbb{N}_n     := \{1,2,3,...,n\}$ die *natürlichen Zahlen der Ordnung $n$*,
* $\mathbb{N}^0     := \mathbb{N} \cup \{0\}$ die *natürlichen Zahlen* und Null,
* $\mathbb{Z}\,\,\, := \{...,-3,-2,-1,0,1,2,3...\}$ die *ganzen Zahlen*,
* $\mathbb{Q}\,\,\, := \{\frac{p}{q}|p,q \in \mathbb{Z}, q \neq 0\}$ die *rationalen Zahlen*,
* $\mathbb{R}\,\,\,$ die *reellen Zahlen*, und
* $\mathbb{C}\,\,\, := \{a +ib|a,b\in \mathbb{R}, i := \sqrt{-1} \}$ die *komplexen Zahlen*.

```

$\mathbb{R}$ umfasst die rationalen Zahlen und die irrationalen Zahlen 
$\mathbb{R}\setminus \mathbb{Q}$ wie z.B. $e,\pi$ und $\sqrt{2}$. Es gilt 

\begin{equation}
\mathbb{N} \subset \mathbb{Z} \subset \mathbb{Q} 
\subset \mathbb{R} \subset \mathbb{C}.
\end{equation}


```{definition, name = "Intervalle"}

Zusammenhängende Teilmengen der reellen Zahlen heißen *Intervalle*. 
Für $a,b\in \mathbb{R}$ unterscheidet man

* das *abgeschlossene Intervall*
\begin{equation}
[a,b] := \{x \in \mathbb{R}|a \le x \le b\},
\end{equation}

* das *offene Interval*
\begin{equation}
]a,b[ := \{x \in \mathbb{R}|a < x < b\},
\end{equation}

* und die *halboffenen Intervalle*
\begin{equation}
]a,b] := \{x \in \mathbb{R}| a < x \le b\} \mbox{ und } 
[a,b[ := \{x \in \mathbb{R}| a \le x < b\}.
\end{equation}

```

Positiv Unendlich ($\infty$) und negativ Unendlich ($-\infty$) sind keine Elemente
von $\mathbb{R}$. Es gilt also immer $]-\infty,b]$ oder $]-\infty,b[$ bzw.
$]a,\infty[$  oder $[a,\infty[$, sowie $\mathbb{R} = ]-\infty, \infty[$.


```{definition, name = "Kartesische Produkte"}

$M$ und $N$ seien zwei Mengen. Dann ist das *Kartesische Produkt der Mengen $M$ 
und $N$* die Menge aller geordneten Tupel $(m,n)$ mit $m \in M$ und $n \in N$, 
formal
\begin{equation}
M \times N := \{(m,n)|m\in M, n \in N \}.
\end{equation}

Das Kartesische Produkt einer Menge $M$ mit sich selbst wird bezeichnet mit
\begin{equation}
M^2 := M \times M.
\end{equation}
Seien weiterhin $M_1, M_2, ..., M_n$ Mengen. Dann ist das *Kartesische Produkt 
der Mengen $M_1,...,M_n$* die Menge aller geordneten $n$-Tupel $(m_1,...,m_n)$ 
mit $m_i \in M_i$ für $i = 1,...,n$, formal
\begin{equation}
\prod_{i=1}^n M_i := M_1 \times \cdots \times M_n := \{(m_1,...,m_n)
                |m_i \in M_i \mbox{ für } i = 1,...,n\}.
\end{equation}
Das $n$-fache Kartesische Produkt einer Menge $M$ mit sich selbst wird bezeichnet mit
\begin{equation}
M^n := \prod_{i=1}^n M := \{(m_1,,...,m_n)|m_i \in M\}.
\end{equation}

```

```{definition, name = "Die Menge der reellen Tupel $n$-ter Ordnung"}

Das $n$-fache Kartesische Produkt der reellen Zahlen mit sich selbst wird 
bezeichnet mit
\begin{equation}
\mathbb{R}^n := \prod_{i=1}^n \mathbb{R} := \{x := (x_1,,...,x_n)|x_i \in \mathbb{R}\}
\end{equation}
und ``$\mathbb{R}$ hoch $n$'' gesprochen. Wir schreiben die Elemente von 
$\mathbb{R}^n$ typischerweise als Spalten
\begin{equation}
x :=
\begin{pmatrix}
x_1
\\
\vdots
\\
x_n
\end{pmatrix}
\end{equation}
und nennen sie *$n$-dimensionale Vektoren*. Zu Abgrenzung nennen wir die 
Elemente von $\mathbb{R}^1 = \mathbb{R}$ auch *Skalare*.

```

Ein Beispiel für $x \in \mathbb{R}^4$ ist 
$x = \begin{pmatrix} 0.16 \\ 1.76 \\ 0.23 \\ 7.10 \end{pmatrix}$.

## Selbstkontrollfragen 

1. Diskutieren Sie den Unterschiede zwischen Definitionen, Theoremen, und Beweisen.
2. Geben Sie die Definition einer Menge nach Cantor (1895) wieder.
3. Nennen Sie drei Möglichkeiten zur Definition einer Menge.
4. Für Mengen $M,N$ erläutern Sie die Ausdrücke $m \in M, m \notin N, M \subseteq N, M \subset N$. 
5. Definieren Sie den Begriff der Kardinalität einer Menge.
6. Definieren Sie den Begriff der Potenzmenge einer Menge.
7. Es sei $M := \{a,b\}$. Bestimmen Sie $\mathcal{P}(M)$.
8. Es seien $M := \{a,b\}, N := \{a,c,d\}$. Bestimmen Sie $M \cup N, M \cap N, M\setminus N, M \Delta N$.
9. Erläutern Sie die Symbole $\mathbb{N}$, $\mathbb{N}_n$, und $\mathbb{N}^0$.
10. Erläutern Sie den Unterschied zwischen $\mathbb{N}$ und $\mathbb{Z}$.
11. Erläutern Sie den Unterschied zwischen $\mathbb{R}$ und $\mathbb{Q}$.
12. Definieren Sie die Begriffe des abgeschlossenen, offenen, und halboffenen Intervalls.
13. Es seien $M$ und $N$ Mengen. Erläutern Sie die Notation $M \times N$.
14. Definieren sie die Menge $\mathbb{R}^n$.

