# Summen, Produkte, Potenzen {#summen}

## Summen

```{definition, name =  "Summenzeichen"}

Summen werden oft mithilfe des \textit{Summenzeichens}
\begin{equation}
\sum_{i=1}^{n} x_i = x_1 + x_{2} + \cdots + x_{n}
\end{equation}
dargestellt. Dabei stehen

* $\Sigma$ für das griechische \textit{S}igma, mnemonisch für \textit{S}umme,
* das Subskript $i = 1$ für den Laufindex der Summanden und den Startindex,
* das Superskript $n$ für den Endindex,
* $x_1, x_2, ..., x_n$ für die Summanden.

```

* Nur mit Subskript und Superskripten macht das Summenzeichen Sinn. 

* Die Bezeichnung des Laufindexes ist irrelevant, es gilt 
\begin{equation}
\sum_{i=1}^n x_i = \sum_{j=1}^n x_j
\end{equation}

* In seltenen Fällen wird der Laufindex auch als Element einer Indexmenge 
angegeben.Ist z.B. die Indexmenge $I := \{1,5,7\}$ definiert, so ist 
\begin{equation}
\sum_{i \in I}x_i := x_1 + x_5 + x_7.
\end{equation}


```{definition, name = "Rechenregeln für Summen"} 

Für Summen gelten folgende Rechenregeln:

* Summen gleicher Summanden
\begin{equation}
\sum_{i=1}^n x = nx
\end{equation}

* Assoziativität bei Summen gleicher Länge
\begin{equation}
\sum_{i=1}^n x_i + \sum_{i=1}^n y_i = \sum_{i=1}^n (x_i + y_i)
\end{equation}

* Distributivität bei Multiplikation mit einer Konstante
\begin{equation}
\sum_{i=1}^n ax_i = a\sum_{i=1}^n x_i
\end{equation}

* Aufspalten von Summen mit $1 < m < n$
\begin{equation}
\sum_{i = 1}^n x_i = \sum_{i=1}^m x_i + \sum_{i=m+1}^n x_i
\end{equation}

* Umindizierung
\begin{equation}
\sum_{i=0}^n x_i = \sum_{j = m}^{n+m} x_{j - m}
\end{equation}

```

## Produkte

```{definition, name =  "Produktzeichen"}

Produkte werden oft mithilfe des *Produktzeichens*
\begin{equation}
\prod_{i=1}^{n} x_i = x_1 \cdot x_{2} \cdot \cdots \cdot x_{n}
\end{equation}
dargestellt. Dabei stehen

* $\prod$ für das griechische \textit{P}i, mnemonisch für \textit{P}rodukt,
* das Subskript $i = 1$ für den Laufindex der Produkterme und den Startindex,
* das Superskript $n$ für den Endindex,
* $x_1, x_2, ..., x_n$ für die Produktterme.

```

* Nur mit Subskript und Superskripten macht das Produktzeichen Sinn.

* Die Bezeichnung des Laufindexes ist irrelevant, es gilt 
\begin{equation}
\prod_{i=1}^n x_i = \prod_{j=1}^n x_j.
\end{equation}

* In seltenen Fällen wird der Laufindex auch als Element einer Indexmenge 
angegeben. Ist z.B. die Indexmenge $J := \mathbb{N}_2^0$ definiert, so ist 
\begin{equation}
\sum_{j \in J}x_j := x_0 + x_1 + x_2.
\end{equation}

## Potenzen

```{definition, name =  "Potenz"}

Für $a \in \mathbb{R}$ und $n \in \mathbb{N}^0$ ist die *$n$-te Potenz von $a$* 
definiert durch
\begin{equation}
a^0 := 1 \mbox{ und } a^{n+1} := a^n \cdot a.
\end{equation}
Weiterhin ist für $a\in \mathbb{R} \setminus 0$ und  $n \in \mathbb{N}^0$ die 
*negative $n$-te Potenz von $a$* definiert durch
\begin{equation}
a^{-n} := (a^n)^{-1} := \frac{1}{a^n}.
\end{equation}
$a$ wird dabei *Basis* und $n$ wird *Exponent* genannt.

```

```{theorem, name = "Rechenregel für Potenzen"}

Für $a,b\in \mathbb{R}$  und $n,m \in \mathbb{Z}$ mit $a\neq 0$ bei negativen
Exponenten gelten folgende Rechenregeln:
\begin{align}
a^n a^m & = a^{n+m} \\
(a^n)^m & = a^{nm}  \\
(ab)^n 	& = a^nb^n
\end{align}

```

```{definition, name =  "$n$-te Wurzel"}

Für $a \in \mathbb{R}$ und $n \in \mathbb{N}$ ist die *$n$-te Wurzel von $a$* 
definiert als die Zahl $r$, so dass 
\begin{equation}
r^n = a.
\end{equation}

```

```{theorem, name =  "Potenzschreibweise der $n$-ten Wurzel"}

Es sei $a \in \mathbb{R}$, $n \in \mathbb{N}$, und $r$ die $n$-te Wurzel von $a$. Dann gilt
\begin{equation}
r = a^{\frac{1}{n}}
\end{equation}
```


```{proof}
Es gilt 
\begin{equation} 
\left(a^{\frac{1}{n}}\right)^n  
= a^{\frac{1}{n}}\cdot a^{\frac{1}{n}}\cdot \cdots \cdot a^{\frac{1}{n}} 
 = a^{\sum_{i=1}^n \frac{1}{n}} 
 = a^1 
= a. 
\end{equation} 
Also gilt mit der Definition der $n$-ten Wurzel, dass $r = a^\frac{1}{n}$.
```

* Das Rechnen mit Quadratwurzeln wird durch $\sqrt{x} = x^{\frac{1}{2}}$ sehr
erleichtert. 

## Selbstkontrollfragen 

1. Berechnen Sie die Summen $\sum_{i=1}^3 2$, $\sum_{i=1}^3 i^2$, und $\sum_{i=1}^3 
\frac{2}{3}i$.
2. Schreiben Sie die Summe $1 + 3 + 5 + 7 + 9 + 11$ mithilfe des Summenzeichens.
3. Schreiben Sie die Summe $0 + 2 + 4 + 6 + 8 + 10$ mithilfe des Summenzeichens.
4. Definieren Sie das Produktzeichen.
5. Für $a \in \mathbb{R}$, definieren Sie die $n$te (negative) Potenz von $a$.
6. Berechnen Sie $2^2\cdot 2^3$ und $2^5$. Geben Sie die zugehörige Potenzregel an.
7. Berechnen Sie $6^2$ und $2^2\cdot 3^2$. Geben Sie die zugehörige Potenzregel an.
8. Warum kann die $n$-te Wurzel von $a$ als $a^{\frac{1}{n}}$ geschrieben werden?
9. Berechnen Sie $(\sqrt{2})^{\frac{2}{3}}, 9^{\frac{1}{2}}$, und $4^{-\frac{1}{2}}$.


